# Generated by Django 5.0.1 on 2024-01-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
