# Generated by Django 5.0.1 on 2024-01-13 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_warehouseemployee_delete_user'),
        ('warehouse', '0004_remove_order_products_quantity_map_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('DEL', 'Delivery'), ('WRH', 'Warehouse'), ('CUS', 'Custom')], default='DEL', max_length=3, null=True)),
                ('description', models.TextField()),
                ('executingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.warehouseemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('DEL', 'Delivery'), ('WRH', 'Warehouse'), ('CUS', 'Custom')], default='DEL', max_length=3, null=True)),
                ('executingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.warehouseemployee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.delivery'),
        ),
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('DEL', 'Delivery'), ('WRH', 'Warehouse'), ('CUS', 'Custom')], default='DEL', max_length=3, null=True)),
                ('executingEmployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.warehouseemployee')),
                ('task_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousetaskitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
