# Generated by Django 5.0.1 on 2024-01-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_remove_warehouseemployee_address_and_more'),
        ('warehouse', '0007_alter_order_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtask',
            name='executingEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.warehouseemployee'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='executingEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.warehouseemployee'),
        ),
        migrations.AlterField(
            model_name='warehousetask',
            name='executingEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.warehouseemployee'),
        ),
    ]
