# Generated by Django 5.0.1 on 2024-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In progress'), ('DON', 'Done')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In progress'), ('DON', 'Done')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='warehousetask',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In progress'), ('DON', 'Done')], default='NEW', max_length=3),
        ),
    ]
