# Generated by Django 5.0.1 on 2024-01-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CLI', 'Client'), ('OFF', 'Office employee'), ('WAR', 'Warehouse employee')], default='CLI', max_length=3)),
            ],
        ),
    ]
