# Generated by Django 5.0.1 on 2024-01-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_warehouseemployee_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CLI', 'Client'), ('OFF', 'Office employee'), ('WAR', 'Warehouse employee')], default='CLI', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='warehouseemployee',
            name='surname',
        ),
        migrations.AddField(
            model_name='warehouseemployee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.user'),
        ),
    ]
