# Generated by Django 5.0.1 on 2024-01-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_remove_warehouseemployee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseemployee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.user'),
        ),
    ]
